Knockback values are updated even if knockback is nullified
comphack/comp_hack pull request #1273
Opened 2020-10-19 23:16 UTC by TallgeeseHeaven

Knockback nullification only comes in to prevent the actual knockback. An extra boolean for targets is given to apply STATUS_ADD_KNOCKBACK tokusei even if they nullify the knockback itself.

Fixes #1256

2020-10-21 02:19 UTC, HACKfrost requested changes

2020-10-21 02:19 UTC, HACKfrost commented on server/channel/src/SkillManager.cpp
> +  bool applyKnockbackStatuses = false;
Capitalize at least, rename if not applying status effects direct from skill from knockback

2020-10-21 02:19 UTC, HACKfrost commented on server/channel/src/SkillManager.cpp
>        if (target.EntityState->StatusRestrictKnockbackCount() > 0) {
This being able to disable it seems odd. I think Fizzy was confident only the source null below should cancel it.

2020-10-21 02:19 UTC, HACKfrost commented on server/channel/src/SkillManager.cpp
> +          }
This can't be moved here. UpdateKnockback has already run so even if they null the knockback, their value has already updated. The logic really does need to be an explicit "current knockback exceeds knockback resist" check I believe.

2020-10-22 08:18 UTC, TallgeeseHeaven commented on server/channel/src/SkillManager.cpp
> +  bool applyKnockbackStatuses = false;
Renamed it to ApplyAddedKnockbackEffects. Is this acceptable?

2020-10-22 08:19 UTC, TallgeeseHeaven commented on server/channel/src/SkillManager.cpp
>        if (target.EntityState->StatusRestrictKnockbackCount() > 0) {
When I spoke to Fizzy about it, neither of us were sure what kind of statuses these were, so we weren't sure what to do here, thus decided to leave it. Can you shed light on this?

2020-10-22 16:30 UTC, HACKfrost commented on server/channel/src/SkillManager.cpp
> +  bool applyKnockbackStatuses = false;
Yes sounds great

2020-10-22 16:41 UTC, HACKfrost commented on server/channel/src/SkillManager.cpp
>        if (target.EntityState->StatusRestrictKnockbackCount() > 0) {
Simplest example is the oh so different "shock" status. Any status that restricts movement and isn't cancelled on hit, damage or knockback is considered a "restrict knockback" status as you can't be knocked back during it. However to me this means it would also serve a secondary function of stopping these other status effects from applying, something I feel is a bit of a stretch. Again if Fizzy is okay with this, I'm fine with how you have it. You are making "shock" more special than it already is though :P

2020-10-24 03:54 UTC, HACKfrost approved these changes

2020-10-24 03:54 UTC, HACKfrost commented on server/channel/src/SkillManager.cpp
> -          if (!kbNull ||
Will never be less than zero but that's fine :P

2020-10-24 16:41 UTC, TallgeeseHeaven commented on server/channel/src/SkillManager.cpp
> -          if (!kbNull ||
Haha, didn't want to assume. Fixed it anyway.

2020-11-23 17:49 UTC, compomega approved these changes

2020-11-23 17:49 UTC, merged