Add cooldown status upon successful completion of Mitama allocation reset.
comphack/comp_hack pull request #1343
Opened 2021-01-14 19:38 UTC by TallgeeseHeaven

Fixes #1341

2021-01-14 20:02 UTC, compomega requested changes

2021-01-14 20:02 UTC, compomega commented on contrib/testing/config/constants.xml
> +	<constant name="STATUS_MITAMA_ALLOCATION_RESET_COOLDOWN">865</constant>
This was indented with a tab character.

2021-01-14 21:37 UTC, TallgeeseHeaven commented on contrib/testing/config/constants.xml
> +	<constant name="STATUS_MITAMA_ALLOCATION_RESET_COOLDOWN">865</constant>
Fixed.

2021-01-15 00:09 UTC, compomega approved these changes

2021-01-15 02:06 UTC, merged