Phantom Destruction: Remote Interactions
comphack/comp_hack pull request #1490
Opened 2022-01-13 11:36 UTC by TallgeeseHeaven

Adds checks so that a client cannot interact with an object beyond the intended maximum interaction distance.

2022-01-13 18:24 UTC, compomega requested changes

2022-01-13 18:24 UTC, compomega commented on server/channel/src/ActiveEntityState.cpp
> +  auto zone = GetZone();
Should you check zone?

2022-01-13 18:24 UTC, compomega commented on server/channel/src/ActiveEntityState.cpp
> +  if (!obj) {
Should you check zone?

2022-01-13 18:24 UTC, compomega commented on server/channel/src/PlasmaState.cpp
> +bool PlasmaState::PickPoint(std::shared_ptr<PlasmaPoint> point,
Pass ```const std::shared_ptr<PlasmaPoint> &point``` so as not to copy the shared pointer or pass the raw pointer since this function is not taking ownership or storing it.

2022-01-13 18:24 UTC, compomega commented on server/channel/src/packets/game/LootBossBox.cpp
> +                 "loot "
Merge this line of text with the line bellow and save again so the formatter reflows the text better.

2022-01-13 18:24 UTC, compomega commented on server/channel/src/packets/game/LootDemonEggData.cpp
> +                 "retrieve its information "
Merge this line of text with the line bellow and save again so the formatter reflows the text better.

2022-01-13 18:24 UTC, compomega commented on server/channel/src/packets/game/LootItem.cpp
> +                 "loot "
Merge this line of text with the line bellow and save again so the formatter reflows the text better.

2022-01-13 18:24 UTC, compomega commented on server/channel/src/packets/game/LootTreasureBox.cpp
> +                 "its information "
Merge this line of text with the line bellow and save again so the formatter reflows the text better.

2022-01-13 18:24 UTC, compomega commented on server/channel/src/packets/game/LootTreasureBox.cpp
> +  } else if (lBox && ((lBox->ValidLooterIDsCount() == 0 &&
This code looks similar to the LootItem code. Could it be refactored?

2022-01-13 18:24 UTC, compomega commented on server/channel/src/packets/game/PlasmaResult.cpp
> +  if (point) {
Is this all that is needed? No interaction check?

2022-01-13 18:24 UTC, compomega commented on server/channel/src/packets/game/PlasmaStart.cpp
> +                   "interact with it "
Merge this line of text with the line bellow and save again so the formatter reflows the text better.

2022-01-14 01:47 UTC, TallgeeseHeaven commented on server/channel/src/ActiveEntityState.cpp
> +  if (!obj) {
From what I saw the stuff that calls CanInteract all check.

2022-01-14 01:52 UTC, TallgeeseHeaven commented on server/channel/src/packets/game/PlasmaResult.cpp
> +  if (point) {
No need, as you can't move anymore once you start the game and that one has an interaction check.

2022-01-14 02:00 UTC, TallgeeseHeaven commented on server/channel/src/packets/game/LootTreasureBox.cpp
> +  } else if (lBox && ((lBox->ValidLooterIDsCount() == 0 &&
Not similar enough.

2022-01-14 23:10 UTC, compomega approved these changes

2022-01-15 00:15 UTC, merged