Phantom Destruction: Basic Item Use +  Entrust + Triple Fusion
comphack/comp_hack pull request #1494
Opened 2022-01-14 03:53 UTC by TallgeeseHeaven

Corrections to various exploits involving phantom item usage and entrusting therein, including triple fusion.

Closes #1364

2022-01-16 16:39 UTC, compomega requested changes

2022-01-16 16:39 UTC, compomega commented on server/channel/src/packets/game/EntrustRequest.cpp
> +                           targetCState->GetCurrentY()) > 700.f)) {
Why is this distance hard coded?

2022-01-17 00:28 UTC, TallgeeseHeaven commented on server/channel/src/packets/game/EntrustRequest.cpp
> +                           targetCState->GetCurrentY()) > 700.f)) {
Added a constant.

2022-01-17 00:44 UTC, compomega approved these changes

2022-01-17 05:22 UTC, merged