Phantom Destruction: Trading
comphack/comp_hack pull request #1496
Opened 2022-01-14 06:19 UTC by TallgeeseHeaven

Remove the ability to initiate trades remotely, the ability to remove items during a locked trade window, and the ability to add phantom items to trades.

2022-01-16 18:32 UTC, compomega requested changes

2022-01-16 18:32 UTC, compomega commented on server/channel/src/packets/game/TradeRequest.cpp
> +                          otherCState->GetCurrentY()) > 1200.f) {
Why is this distance hard coded?

2022-01-17 06:15 UTC, TallgeeseHeaven commented on server/channel/src/packets/game/TradeRequest.cpp
> +                          otherCState->GetCurrentY()) > 1200.f) {
Constant added.

2022-01-17 06:27 UTC, compomega approved these changes

2022-01-17 07:43 UTC, merged